import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  AlignmentType,
  BorderStyle,
} from "docx";

interface DocumentData {
  title: string;
  date: string;
  toName: string;
  toAddress?: string;
  fromName: string;
  fromAddress?: string;
  fromPhone?: string;
  subject: string;
  body: string;
  documentType: string;
}

export async function generateLegalDOCX(data: DocumentData): Promise<Buffer> {
  const doc = new Document({
    sections: [
      {
        properties: {},
        children: [
          new Paragraph({
            children: [
              new TextRun({
                text: "NyayaBot — Free AI Legal Aid Service",
                bold: true,
                size: 18,
                color: "1F293D",
              }),
            ],
            alignment: AlignmentType.CENTER,
            border: {
              bottom: { style: BorderStyle.SINGLE, size: 6, color: "1F293D" },
            },
            spacing: { after: 200 },
          }),

          new Paragraph({
            children: [
              new TextRun({
                text: `[${data.documentType}]     Date: ${data.date}`,
                size: 18,
                color: "555555",
              }),
            ],
            spacing: { after: 240 },
          }),

          new Paragraph({
            text: data.title,
            heading: HeadingLevel.HEADING_1,
            spacing: { after: 240 },
          }),

          new Paragraph({
            children: [new TextRun({ text: "To:", bold: true, size: 22 })],
          }),
          new Paragraph({
            children: [new TextRun({ text: data.toName, size: 22 })],
          }),
          ...(data.toAddress
            ? [
                new Paragraph({
                  children: [new TextRun({ text: data.toAddress, size: 22 })],
                  spacing: { after: 200 },
                }),
              ]
            : []),

          new Paragraph({
            children: [
              new TextRun({ text: "Subject: ", bold: true, size: 22 }),
              new TextRun({ text: data.subject, size: 22 }),
            ],
            spacing: { after: 200 },
            border: {
              bottom: { style: BorderStyle.SINGLE, size: 2, color: "CCCCCC" },
            },
          }),

          ...data.body.split("\n").map(
            (line) =>
              new Paragraph({
                children: [new TextRun({ text: line, size: 22 })],
                spacing: { after: 120 },
              })
          ),

          new Paragraph({ spacing: { before: 400 } }),
          new Paragraph({
            children: [new TextRun({ text: "Yours faithfully,", size: 22 })],
          }),
          new Paragraph({
            children: [new TextRun({ text: data.fromName, bold: true, size: 22 })],
          }),
          ...(data.fromAddress
            ? [
                new Paragraph({
                  children: [
                    new TextRun({ text: data.fromAddress, size: 22 }),
                  ],
                }),
              ]
            : []),
          ...(data.fromPhone
            ? [
                new Paragraph({
                  children: [
                    new TextRun({
                      text: `Phone: ${data.fromPhone}`,
                      size: 22,
                    }),
                  ],
                }),
              ]
            : []),

          new Paragraph({
            children: [
              new TextRun({
                text: "This document was generated by NyayaBot — free AI legal aid. It does not constitute legal advice.",
                size: 16,
                color: "888888",
                italics: true,
              }),
            ],
            spacing: { before: 600 },
            border: {
              top: { style: BorderStyle.SINGLE, size: 2, color: "CCCCCC" },
            },
          }),
        ],
      },
    ],
  });

  return Packer.toBuffer(doc);
}
