import { jsPDF } from "jspdf";

interface DocumentData {
  title: string;
  date: string;
  toName: string;
  toAddress?: string;
  fromName: string;
  fromAddress?: string;
  fromPhone?: string;
  subject: string;
  body: string;
  footer?: string;
  documentType: string;
}

export function generateLegalPDF(data: DocumentData): Buffer {
  const doc = new jsPDF({
    orientation: "portrait",
    unit: "mm",
    format: "a4",
  });

  const PAGE_W = 210;
  const MARGIN = 20;
  const CONTENT_W = PAGE_W - MARGIN * 2;
  let y = 20;

  doc.setFillColor(31, 41, 61);
  doc.rect(0, 0, PAGE_W, 14, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("NyayaBot — AI Legal Aid", MARGIN, 9);
  doc.text(`nyayabot.in  |  Free Legal Aid`, PAGE_W - MARGIN, 9, { align: "right" });

  y = 24;

  doc.setFillColor(230, 240, 255);
  doc.setTextColor(31, 41, 61);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  doc.roundedRect(MARGIN, y, 50, 6, 1, 1, "F");
  doc.text(data.documentType.toUpperCase(), MARGIN + 3, y + 4);
  y += 12;

  doc.setTextColor(100, 100, 100);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(data.date, PAGE_W - MARGIN, y, { align: "right" });

  doc.setTextColor(10, 10, 10);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text(data.title, MARGIN, y + 10);
  y += 20;

  doc.setDrawColor(200, 200, 200);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(31, 41, 61);
  doc.text("TO:", MARGIN, y);
  y += 5;
  doc.setFont("helvetica", "normal");
  doc.setTextColor(50, 50, 50);
  doc.text(data.toName, MARGIN, y);
  y += 5;
  if (data.toAddress) {
    const toAddrLines = doc.splitTextToSize(data.toAddress, CONTENT_W - 30);
    doc.text(toAddrLines, MARGIN, y);
    y += toAddrLines.length * 5;
  }
  y += 5;

  doc.setFont("helvetica", "bold");
  doc.setTextColor(31, 41, 61);
  doc.text("SUBJECT: ", MARGIN, y);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(50, 50, 50);
  const subjectLines = doc.splitTextToSize(data.subject, CONTENT_W - 30);
  doc.text(subjectLines, MARGIN + 22, y);
  y += Math.max(subjectLines.length * 5, 6) + 5;

  doc.setDrawColor(220, 220, 220);
  doc.line(MARGIN, y, PAGE_W - MARGIN, y);
  y += 8;

  doc.setFontSize(11);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(30, 30, 30);
  const bodyLines = doc.splitTextToSize(data.body, CONTENT_W);
  doc.text(bodyLines, MARGIN, y);
  y += bodyLines.length * 5.5 + 10;

  doc.setFontSize(10);
  doc.setFont("helvetica", "bold");
  doc.text("Yours faithfully,", MARGIN, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.text(data.fromName, MARGIN, y);
  y += 5;
  if (data.fromAddress) doc.text(data.fromAddress, MARGIN, y), (y += 5);
  if (data.fromPhone) doc.text(`Phone: ${data.fromPhone}`, MARGIN, y), (y += 5);

  const footerText =
    data.footer ||
    "This document was generated by NyayaBot — a free AI legal aid service. It does not constitute legal advice. For complex matters, consult a qualified advocate.";
  doc.setFontSize(8);
  doc.setTextColor(140, 140, 140);
  const footerLines = doc.splitTextToSize(footerText, CONTENT_W);
  const footerY = 287 - footerLines.length * 4;
  doc.setDrawColor(200, 200, 200);
  doc.line(MARGIN, footerY - 3, PAGE_W - MARGIN, footerY - 3);
  doc.text(footerLines, MARGIN, footerY);

  return Buffer.from(doc.output("arraybuffer"));
}
